import port1 from "../img/portImages/maya-1.jpg";
import port2 from "../img/portImages/port1.jpg";
import port3 from "../img/portImages/port2.jpg";
import port4 from "../img/portImages/port3.jpg";
import port6 from "../img/portImages/port5.jpg";

const portfolios = [
  {
    id: 1,
    category: "Python",
    link: "https://github.com/vongovantien/FlaskStore",
    icon: "Visit",
    image: port1,
    title: "WebSite Ban Dien Thoai",
    tech: "Flask, PostgreSQL",
  },
  {
    id: 2,
    category: "Python",
    link: "https://github.com/vongovantien/DjangoCareerApp",
    icon: "Visit",
    image: port2,
    title: "Viet API Tuyen Dung Viec Lam",
    tech: "Django, MySQL, Django Rest Framework",
  },
  // {
  //   id: 3,
  //   category: "PHP",
  //   link: "https://github.com/vongovantien/eshopapp",
  //   icon: "Visit",
  //   image: port3,
  //   title: "WebSite Ban Nuoc Hoa Nam Nu",
  //   tech: "Laravel, MySql",
  // },
  {
    id: 4,
    category: "PHP",
    link: "https://github.com/vongovantien/QuanLiXaydung",
    icon: "Visit",
    image: port3,
    title: "Quan Li Cua Hang Xay Dung",
    tech: "Laravel, MySql",
  },
  {
    id: 5,
    category: "React Js",
    link: "https://github.com/vongovantien/QuanLiXaydung",
    icon: "Visit",
    image: port4,
    title: "Website Tuyen Dung Viec Lam",
    tech: "ReactJS, Redux",
  },
  // {
  //   id: 6,
  //   category: "Java",
  //   link: "https://github.com/vongovantien/JavaCareerApp",
  //   icon: "Visit",
  //   image: port4,
  //   title: "Website Tuyen Dung Viec Lam",
  //   tech: "SpringMVC, Hibernate",
  // },
  {
    id: 7,
    category: "Python",
    link: "https://github.com/vongovantien/JavaCareerApp",
    icon: "Visit",
    image: port4,
    title: "Website Ban Sach",
    tech: "Flask, MySql",
  },
  // {
  //   id: 8,
  //   category: "PHP",
  //   link: "www.youtube.com",
  //   icon: "Visit",
  //   image: port6,
  //   title: "Viet API Blog",
  //   tech: "Laravel, MySql",
  // },
  // {
  //   id: 9,
  //   category: "UX/UI",
  //   link: "www.youtube.com",
  //   icon: "Visit",
  //   image: port4,
  //   title: "Template Website Coffee",
  //   tech: "Figma",
  // },
  // {
  //   id: 10,
  //   category: "C#",
  //   link: "www.youtube.com",
  //   icon: "Visit",
  //   image: port6,
  //   title: "Website Ban Rau Cu",
  //   tech: "EF, MSSQL, MVC Core",
  // },
  {
    id: 11,
    category: "C#",
    link: "www.youtube.com",
    icon: "Visit",
    image: port6,
    title: "Website Ban Thiet Bi Dien",
    tech: "EF, MSSQL, MVC5",
  },
  {
    id: 12,
    category: "JavaScript",
    link: "www.youtube.com",
    icon: "Visit",
    image: port6,
    title: "Website Gioi thieu Dich Vu Xe Hoi",
    tech: "HTML, CSS, JavaScript, jQuery",
  },
];

export default portfolios;
